# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: "Worker"

steps:
- task: SqlDacpacDeploymentOnMachineGroup@0
  inputs:
    TaskType: 'sqlInline'
    InlineSql: 'SELECT * FROM Entry'
    ServerName: 'events-server.database.windows.net'
    DatabaseName: 'EventsV2'
    AuthScheme: 'sqlServerAuthentication'
    SqlUsername: 'adminuser'
    SqlPassword: 'ProiectING00'
